- name: deploiement serveur web
  hosts: webserver
  become: true

  tasks:
  - name: install heartbeat
    apt:
      name: heartbeat

  - name: envoie des fichiers de configurations
    copy:
      src: config/{{ item }}
      dest: /etc/ha.d/{{ item }}
      loop:
        - ha.cf
        - authkeys
 
 - name: envoi du fichier haressources
   template:
     src: config/harresources
     dst: /etc.ha.d/haressources
  
  - name: donner les droits au fichier authkeys
    file:
      path: /etc/ha.d/authkeys
      mode: '0600'

 - name: restart heartbeat service
      service: name=heartbeat state=restarted
 
 - name: verifier que heartbeat est en route
      service: name=heartbeat state=started enabled=yes 
