---
- hosts: mariadb-server
  become: true
  vars:
    mysql_root_password: linux
  tasks:
    - name: Installation de MariaDB
      apt:
        name:
          - mariadb-server
        state: latest

    - name: Autoriser connexion distantes
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address            = 127.0.0.1'
        line: ' bind-address              = 0.0.0.0'

    - name: Ensure mariadb service is start
      service:
        name: mariadb
        state: started
        enabled: yes
